name: CD
on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/cd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_CLOUDRUN_SA }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Build container
        working-directory: app
        run: |
          gcloud builds submit \
            --pack image=us-west1-docker.pkg.dev/gcp-agents-tests/web-app/accident-reports-frontend:latest

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy accident-reports-frontend \
            --image us-west1-docker.pkg.dev/gcp-agents-tests/web-app/accident-reports-frontend:latest \
            --region us-west1 --platform managed --allow-unauthenticated \
            --set-env-vars GCS_BUCKET=accident-reports-artifacts,NODE_ENV=production

      - name: Smoke test
        run: |
          URL=$(gcloud run services describe accident-reports-frontend --region us-west1 --format='value(status.uri)')
          curl -f "$URL/healthz"
