name: CD
on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/cd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          audience: https://github.com/${{ github.repository_owner }}
          service_account: ${{ secrets.GCP_CLOUDRUN_SA }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Build and Deploy to Cloud Run
        id: deploy
        run: |
          URL=$(gcloud run deploy accident-reports-frontend \
            --source ./app \
            --region us-west1 --platform managed --allow-unauthenticated \
            --set-env-vars GCS_BUCKET=accident-reports-artifacts,NODE_ENV=production \
            --format='value(uri)')
          echo "url=$URL" >> "$GITHUB_OUTPUT"

      - name: Smoke test
        run: curl -f "${{ steps.deploy.outputs.url }}/healthz"
