name: CI
on:
  pull_request:
    paths:
      - 'app/**'
      - 'schemas/**'
      - '.github/workflows/ci.yml'
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --ci
      - run: npm run build
      - name: Schema validate (Ajv)
        run: node ../scripts/validate-artifacts.js
