name: Terraform
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'infra/**'
      - '.github/workflows/tf-plan-apply.yml'

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_TERRAFORM_SA }}
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: |
          terraform -chdir=infra init \
            -backend-config="bucket=${{ vars.GCP_PROJECT_ID }}-tf-state" \
            -backend-config="prefix=terraform/state"
      - run: terraform -chdir=infra plan -input=false
  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_TERRAFORM_SA }}
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: |
          terraform -chdir=infra init -upgrade \
            -backend-config="bucket=${{ vars.GCP_PROJECT_ID }}-tf-state" \
            -backend-config="prefix=terraform/state"
      - run: terraform -chdir=infra apply -auto-approve -input=false
